const ADD_TO_BASKET = "ADD_TO_BASKET";
const DELETE_FROM_BASKET = "DELETE_FROM_BASKET";
const CLEAR_USER_BASKET = "CLEAR_USER_BASKET";

export default {
    ADD_TO_BASKET,
    DELETE_FROM_BASKET,
    CLEAR_USER_BASKET
}

